

Interceptors are an excellent way to modify the HTTP request or response to make it more simple and understandable.

How Does The Interceptor Work?
Assume we need to do some operation on each request sent through httpClient in the application.

For example, we must provide an auth token in each request so that the server can
 authenticate and deliver us the required answer.
  To do this, we will establish a service in between that will allow us to modify our 
  httpRequest or httpResponse accordingly. 


How To Create A Simple HTTP Interceptor
Angular interceptor can be created using the following command:

ng generate interceptor ExampleInterceptor
#)An angular interceptor will look the same as a service with @Injectable(), which implements HttpInterceptor, which has a method called intercept that allows you to intercept the HTTP request and response.

import { Injectable } from '@angular/core';
import { HttpInterceptor, HttpEvent, HttpRequest, HttpHandler } from '@angular/common/http';
import { Observable } from 'rxjs';

@Injectable()
export class ExampleInterceptor implements HttpInterceptor {
  intercept(httpRequest: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
      //any alteration in httpRequest can be done here
    return next.handle(httpRequest);
  }
}



Here, Angular gives a reference to the httpRequest object when the intercept() function is used. We can review and alter this request as required. When our logic is finished, we use next.handle and send the revised request back to the application.


@NgModule({
   providers: [
     { 
       provide: HTTP_INTERCEPTORS, useClass: ExampleInterceptor, multi:true
     },
],})




#)Can We Have Multiple Interceptors?
Ans)Yes, you may declare many interceptors in the application, each with its own scope of action.
For example, you may design one interceptor that is exclusively responsible for setting the authentication header, another for error handling, and so on.

To utilise several angular interceptors, use multi:true when registering in @NgModule.

@NgModule({
   providers: [
     { 
       provide: HTTP_INTERCEPTORS, useClass: AuthInterceptor, multi:true,
       provide: HTTP_INTERCEPTORS, useClass: ErrorHandlerInterceptor, multi:true,
       ...  
     },
]})




#)There are multiple real-time senarios where angular interceptors can be really useful:

Modify HTTP headers
Modifying the request body
Set authentication/authorization token
Modify the HTTP response
Error handling
Change the Requested URL



////
package-lock. json is a file that is automatically generated by npm when a package is installed.
It records the exact version of every installed dependency, including its sub-dependencies
and their versions.27
It locks down the specific versions of every installed package, preventing unintended updates.


///
package.json serves as a manifest file for Node projects, containing metadata about the project
and its dependencies.
It includes information such as the project name, 
version, entry point, scripts, and dependencies.



