#)WHat is Java 
Java is High-Level object-oriented programming Language.
High-level-lanagage     ====>  ByteCode   ====> Native Code


Java used object and clasess 


#)WHat are JDK JRE & JVM ? How a java Program  compiled or excuted?  (V.IMP)?

#)What is compile Time and Runtime?
=>CompileTime: 
COmpile Time is the phase during which java source code is translate into ByteCode bt the java compiler(javac).

=>Runtime:
 runtime refers  to the phase during which the jvm excutes the comoplted bytecode .

 ==========================
 Main Featrure 
 1)Platform Indepeendent
 becoz of the byecode it can run in any operating system.
 2)Object oriented:
  Supported  encapsulation ,inheritance  and polymorphism 
 3)Robust and secure. 
 robust becoz automatically memory  mangement we do not need to 
 4)MutlitHReading 
 5) Rich standard library  
 suppose u want to perform sorting ,fitering so we nedd so java provide lot of inbuilt libray.


 #)How java is platform Indepenedent ?WHy convert java code to byteCode?
 java achieves Independent  by compiling source code into bytecode  which can run on any platform
 with a  compatible jvm.

 #) What  is main method in java ? What is the role of public static and void in it ?
  => Main  method is first mehtod in java program.
  => Main method is entry point of the  application.
   
   public  is  access  modifier specifier  main method  acces outside of the class  becoz of public .
   that why jvm acces out main program from outside .
   if main is private then not acces  outside  main method private

   static =>we can call direclty without making object of that method.

   void : void means  main method does not return any value.


#)what is java bytecode ? what is high level , low level code ?
java bytecode is a platform-Indepeendent intermediate code generated by the  java compiler(javac).

java (High level code)

Byte Code (Intermedidate code)

Native Code/Machine code(Low-level code).



















